// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class Member
    {
        public Member()
        {
            Carts = new HashSet<Cart>();
            Evaluations = new HashSet<Evaluation>();
            Orders = new HashSet<Order>();
        }

        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public string NickName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public bool Gender { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public string Salt { get; set; }
        public bool IsActived { get; set; }
        public string ConfirmGuid { get; set; }

        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}