// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147thGraduationTopic.EFModels
{
    public partial class OrderWithMember
    {
        public int OrderId { get; set; }
        public int MemberId { get; set; }
        public int PaymentMethodId { get; set; }
        public DateTime PurchaseTime { get; set; }
        public int? PaymentAmount { get; set; }
        public string Remark { get; set; }
        public string PaymentMethodName { get; set; }
    }
}