// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class CartItems
    {
        public int CartItemId { get; set; }
        public int CartId { get; set; }
        public int SpecId { get; set; }
        public int Quantity { get; set; }

        public virtual Carts Cart { get; set; }
        public virtual Specs Spec { get; set; }
    }
}