// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class Carts
    {
        public Carts()
        {
            CartItems = new HashSet<CartItems>();
        }

        public int CartId { get; set; }
        public int MemberId { get; set; }

        public virtual Members Member { get; set; }
        public virtual ICollection<CartItems> CartItems { get; set; }
    }
}