// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class CouponOwner
    {
        public int CouponId { get; set; }
        public string CouponSerialNumber { get; set; }
        public int MemberId { get; set; }

        public virtual Coupon Coupon { get; set; }
        public virtual Member Member { get; set; }
    }
}