// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class CouponOwners
    {
        public int CouponId { get; set; }
        public string CouponSerialNumber { get; set; }
        public int MemberId { get; set; }

        public virtual Coupons Coupon { get; set; }
        public virtual Members Member { get; set; }
    }
}