// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class Coupons
    {
        public Coupons()
        {
            UsedCoupons = new HashSet<UsedCoupons>();
        }

        public int CouponId { get; set; }
        public int CouponEligibleTagId { get; set; }
        public DateTime CouponStartDate { get; set; }
        public DateTime CouponEndDate { get; set; }
        public int CouponTypeId { get; set; }
        public decimal? CouponDiscountCondition { get; set; }
        public decimal CouponRebate { get; set; }

        public virtual Tags CouponEligibleTag { get; set; }
        public virtual ICollection<UsedCoupons> UsedCoupons { get; set; }
    }
}