// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class Evaluations
    {
        public int EvaluationId { get; set; }
        public int MerchandiseId { get; set; }
        public int MemberId { get; set; }
        public int OrderId { get; set; }
        public string Comment { get; set; }
        public string ImageUrl { get; set; }
        public int Score { get; set; }

        public virtual Members Member { get; set; }
        public virtual Merchandises Merchandise { get; set; }
        public virtual Orders Order { get; set; }
    }
}