// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class Members
    {
        public Members()
        {
            Carts = new HashSet<Carts>();
            Evaluations = new HashSet<Evaluations>();
            Orders = new HashSet<Orders>();
        }

        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public string NickName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public bool Gender { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }

        public virtual ICollection<Carts> Carts { get; set; }
        public virtual ICollection<Evaluations> Evaluations { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}