// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class Merchandises
    {
        public Merchandises()
        {
            Evaluations = new HashSet<Evaluations>();
            Specs = new HashSet<Specs>();
        }

        public int MerchandiseId { get; set; }
        public string MerchandiseName { get; set; }
        public int BrandId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public bool Display { get; set; }

        public virtual Brands Brand { get; set; }
        public virtual Categories Category { get; set; }
        public virtual ICollection<Evaluations> Evaluations { get; set; }
        public virtual ICollection<Specs> Specs { get; set; }
    }
}