// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class MerchandiseTags
    {
        public int MerchandiseId { get; set; }
        public int TagId { get; set; }

        public virtual Merchandises Merchandise { get; set; }
        public virtual Tags Tag { get; set; }
    }
}