// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class OrderLists
    {
        public int OrderListId { get; set; }
        public int OrderId { get; set; }
        public int SpecId { get; set; }
        public int Quantity { get; set; }

        public virtual Orders Order { get; set; }
        public virtual Specs Spec { get; set; }
    }
}