// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class Orders
    {
        public Orders()
        {
            Evaluations = new HashSet<Evaluations>();
            OrderLists = new HashSet<OrderLists>();
            UsedCoupons = new HashSet<UsedCoupons>();
        }

        public int OrderId { get; set; }
        public int MemberId { get; set; }
        public int PaymentMethodId { get; set; }
        public bool Payed { get; set; }
        public DateTime PurchaseTime { get; set; }
        public int? PaymentAmount { get; set; }
        public string DeliveryAddress { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string Remark { get; set; }

        public virtual Members Member { get; set; }
        public virtual PaymentMethods PaymentMethod { get; set; }
        public virtual ICollection<Evaluations> Evaluations { get; set; }
        public virtual ICollection<OrderLists> OrderLists { get; set; }
        public virtual ICollection<UsedCoupons> UsedCoupons { get; set; }
    }
}