// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT147.Estore.DataLayer.EFModels
{
    public partial class Specs
    {
        public Specs()
        {
            CartItems = new HashSet<CartItems>();
            OrderLists = new HashSet<OrderLists>();
        }

        public int SpecId { get; set; }
        public string SpecName { get; set; }
        public int MerchandiseId { get; set; }
        public int Price { get; set; }
        public int Amount { get; set; }
        public int DisplayOrder { get; set; }
        public bool OnShelf { get; set; }
        public int DiscountPercentage { get; set; }

        public virtual Merchandises Merchandise { get; set; }
        public virtual ICollection<CartItems> CartItems { get; set; }
        public virtual ICollection<OrderLists> OrderLists { get; set; }
    }
}